# Generated by Django 5.0.4 on 2024-04-22 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToFundapp', '0003_donation_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='fund',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ToFundapp.fund'),
        ),
    ]
